name: quote_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.3
  share_extend: ^2.0.0
  flutter_wallpaper_manager: ^0.0.4
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - Assets/Images/
    - Assets/Images/Motivation/
    - Assets/Images/Minimalist/
    - Assets/Images/ColorGradient_Images/
    - Assets/Images/Luxury/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: t1
      fonts:
        - asset: Assets/textfiles/t1.ttf
    - family: t2
      fonts:
        - asset: Assets/textfiles/t2.ttf
    - family: t3
      fonts:
        - asset: Assets/textfiles/t3.ttf
    - family: t4
      fonts:
        - asset: Assets/textfiles/t4.ttf
    - family: t5
      fonts:
        - asset: Assets/textfiles/t5.ttf
    - family: t6
      fonts:
        - asset: Assets/textfiles/t6.ttf
    - family: t7
      fonts:
        - asset: Assets/textfiles/t7.ttf
    - family: t8
      fonts:
        - asset: Assets/textfiles/t8.ttf
    - family: t9
      fonts:
        - asset: Assets/textfiles/t9.ttf
    - family: t10
      fonts:
        - asset: Assets/textfiles/t10.ttf
    - family: t11
      fonts:
        - asset: Assets/textfiles/t11.ttf
    - family: t12
      fonts:
        - asset: Assets/textfiles/t12.ttf
    - family: t13
      fonts:
        - asset: Assets/textfiles/t13.ttf
    - family: t14
      fonts:
        - asset: Assets/textfiles/t14.ttf
    - family: t15
      fonts:
        - asset: Assets/textfiles/t15.ttf
    - family: t16
      fonts:
        - asset: Assets/textfiles/t16.ttf
    - family: t17
      fonts:
        - asset: Assets/textfiles/t17.ttf
    - family: t18
      fonts:
        - asset: Assets/textfiles/t18.ttf
    - family: t19
      fonts:
        - asset: Assets/textfiles/t19.ttf
    - family: t20
      fonts:
        - asset: Assets/textfiles/t20.ttf
    - family: t21
      fonts:
        - asset: Assets/textfiles/t21.ttf
    - family: t22
      fonts:
        - asset: Assets/textfiles/t22.ttf
    - family: t23
      fonts:
        - asset: Assets/textfiles/t23.ttf
    - family: t24
      fonts:
        - asset: Assets/textfiles/t24.ttf
    - family: t25
      fonts:
        - asset: Assets/textfiles/t25.ttf
    - family: t26
      fonts:
        - asset: Assets/textfiles/t26.ttf
    - family: t27
      fonts:
        - asset: Assets/textfiles/t27.ttf
    - family: t28
      fonts:
        - asset: Assets/textfiles/t28.ttf
    - family: t29
      fonts:
        - asset: Assets/textfiles/t29.ttf
    - family: t30
      fonts:
        - asset: Assets/textfiles/t30.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
